cli:
  server:
    port: 9090
    bind: 127.0.0.1
    leader: true
  cloud:
    name: Test
    addr: http://127.0.0.1:9090/cloud
    group:  test
    cluster:  test
  log:
    console:
      logLevel: info
    file:
     logPath: ./logs/cloudCli.log
  db:
    badger:
      path: d:/work/db2
  node: CronNode,ProfileInspect
  timer:
    sysTask: '*/2 * * * *'
    profileInspect: '*/20 * * * *'
#  nacos:
#    addr: http://localhost:8848/nacos
#    nameSpace: test
#    logDir: /log/nacos
#    cacheDir: /nacos/cache
  profile-inspect:
    config: profile.json