cli:
  log:
    console:
      logLevel: info
    file:
      logPath: ./logs/cloudCli.log
  db:
    badger:
      path: d:/work/db2
  node: CronNode
  timer:
    ConfigGuard: 0/20 * * * *
    InpectNode: 0/40 * * * *