cli:
  log:
    console:
      logLevel: info
    file:
      logPath: ./logs/cloudCli.log
  db:
    badger:
      path: d:/work/db2
  node: CronNode
  timer:
    ConfigGuard: 0/20 * * * *
    InpectNode: 0/40 * * * *
  nacos:
    addr: http://127.0.0.1:8086/nacos
    namespace: test
    logDir: /log/nacos
    cacheDir: /nacos/cache
  inpect:
    profile: