cli:
  server:
    port: 9090
  cloud:
    name: Test
    ip: 127.0.0.1
    group:  test
    cluster:  test
  log:
    console:
      logLevel: info
    file:
      logPath: ./logs/cloudCli.log
  db:
    badger:
      path: d:/work/db2
  node: CronNode,ProfileInspect
  timer:
    sysTask: '*/10 * * * *'
    profileInspect: '*/15 * * * *'
  nacos:
    addr: http://localhost:8848/nacos
    nameSpace: test
    logDir: /log/nacos
    cacheDir: /nacos/cache
  profile-inspect:
    config: profile.json