cli:
  log:
    console:
      logLevel: info
    file:
      logPath: ./logs/cloudCli.log
  db:
    badger:
      path: d:/work/db2
  node: CronNode
  timer:
    configGuard: 0/20 * * * *
    inpectNode: 0/40 * * * *
  nacos:
    addr: http://localhost:8848/nacos
    nameSpace: test
    logDir: /log/nacos
    cacheDir: /nacos/cache
  inpect:
    profile: profile.json